### PR TITLE
Configures all async operations with .ConfigureAwait(false)

### LINKED ISSUE #1: Async optimizations
Hey,

I noticed that you could improve the library. Please take a look here and tell me what do you think?

https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

### PR DESCRIPTION
**Pull request by mynkow**
The important commit is about async (...).ConfigureAwait(false)

It fixes #1

### CODE REVIEW

**Comment by mynkow** [comment]
Hey @nla-brandonjames 

could you please take a look at this PR

thank you

**Comment by nla-brandonjames** [comment]
I think this will be okay. I will have to configure the tests in a way where they run for anyone who modifies this library.

**Comment by mynkow** [comment]
Do you plan to release this one?

**Comment by nla-brandonjames** [comment]
I've been out of the office. I'm just now getting to this. Also am attempting to fix unit testing at the same time.

**Comment by nla-brandonjames** [comment]
Just released a new update and sent it to NuGet. I made some changes as well. Now the build will show as passing.

**Comment by mynkow** [comment]
thank you very much, appreciated

**Pull request merged**
