### PR TITLE
Fix to TimeZone handling, Fulfillment & Shipment models, added support for .net4.5 - .net4.6.2

### PR DESCRIPTION
**Pull request by vlad-kurdesov**
We will start using this library on production next week. Those changes fix problems I run into while testing. We have our own CI build and private nuget with beta package (to speed up test/release time), but my end goal is to use public package from nuget.

### CODE REVIEW

**Comment by nla-brandonjames** [comment]
I accepted this pull request but testing fails because a target framework is not selected. I still have not published the package to NuGet. I have been busy working on an application so our sales people can submit items to publish quicker.

**Comment by nla-brandonjames** [comment]
I figured out how to publish the correct framework of the library to AppVeyor but now I can't even build the project on my own machine.

**Comment by vlad-kurdesov** [comment]
Thank you. 
CI that I mentioned in my original post, does next 3 commands:
1) dotnet build ShipStation4Net\ShipStation4Net.csproj /p:configuration=debug
2) dotnet pack ShipStation4Net\ShipStation4Net.csproj /p:Configuration=debug /p:PackageVersion=... --verbosity Normal
3) nuget push *.nupkg -src ... -apikey ... -NonInteractive
and it works on build agent which has build tools for VS2017 installed (msbuild15). I could also compile solution on my own machine via VS2017
not sure why it doesn't build now on yours

**Comment by nla-brandonjames** [comment]
Hey sorry about all my superfluous commits. I'm trying very hard to get CI to automatically push builds when they work so I don't have to attend this library when contributors push working builds. I'm frustrated because I'm figuring out the tool all on my own.

**Comment by vlad-kurdesov** [comment]
let me know if I could assist anyhow with that.
I'm not very familiar with AppVeyor + I'm not in aware what is current setup. Most of experience I have with CI is with VSO build agents.
You could also squash all your commits in single one once you get CI to point where it works as you'd like it to work (e.g. `git rebase -i HEAD~20`) - I know that force pushes are not good, but in this case it's one-time deal.

**Comment by nla-brandonjames** [comment]
Thanks,
I appreciate that. I will probably squash my commits down and reset the version of this library back to an earlier one. So, in about 3-4 weeks I will begin to use my libraries again as an important member of the application I've been working on the past few months. In this manner, I will be increasing priority they all are working properly. I hope I won't have to do too much maintenance to them since I want to make progress on my project as a whole, but I should be doing testing on the products API primarily.

**Pull request merged**
